### ISSUE TITLE
Discussion of the list

### ISSUE THREAD

**Issue by dvmason** [jeceljr/SmalltalkSurvey#1]
Thanks, Jecel, for this!

Another one to include is Redline Smalltalk - https://github.com/redline-smalltalk/redline-smalltalk
Speaking of which, if you go to [search on github](https://github.com/search?o=desc&p=2&q=smalltalk&s=stars&type=Repositories) I get 2600 hits... many of which seem to be actual Smalltalk implementations. You can reduce by about 50% by choosing Smalltalk as the language on the left, but this may remove interesting things.

I think adding a column for a URL to a repo or paper or wayback would be much appreciated... as you're uncovering those as you go, anyway.

**Comment by jeceljr** [comment]
I have now included Redline, thanks! Also thanks for the search, - it will take me a while to go through it.

My idea was to have a separate page for each Smalltalk with details and references. That page would include links to papers and repositories. But you are right that a direct link from the table in the main page is a good idea. When the license column is "open" that could be the link. The name will be the link to the detailed page in this repository, so it can't be used for that.

**Comment by jeceljr** [comment]
I have now added the links to the repositories listed in the first 3 pages of the search. This worked out reasonably well - thanks for the suggestion. Only 97 pages to go....

**Comment by dvmason** [comment]
Thanks!
I didn't mean to put an onus on you to go through 2600 entries!
This one looks interesting: https://github.com/0x7CFE/llst
Zag is here: https://github.com/dvmason/Zag-Smalltalk

**Comment by jeceljr** [comment]
Thanks for the two links. I have now added them to the list.

About the search, I expect most interesting results to be in the first 10 pages or so. If that is the case then going through the remaining 100 pages will be very little work.

**Comment by jeceljr** [comment]
I just finished going through all the projects in the github search and added most, but not all to the list.
